#!/bin/bash

set -e

./gradlew check installDist

# TODO:
# - enable
#if [ "${TRAVIS_BRANCH}" == "master" ]; then 
#	./gradlew integrationTest
#	./gradlew jacocoIntegrationTestReport
#	
#	# For coverage badges 
#	bash <(curl -s https://codecov.io/bash)
#fi

./gradlew javadoc
