name: Build gradle project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 10 1,15 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install JDK
      run: ./script/installjdk
    - name: Build with Gradle
      run: ./gradlew -PossrhUsername="" -PossrhPassword="" test dependencyCheckAnalyze
      env:
          JAVA_HOME: /home/runner/corretto-8/
