name: Build gradle project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install JDK
      run: ./script/installjdk
    - name: Build with Gradle
      run: ./gradlew build
      env:
          JAVA_HOME: /home/runner/corretto-8/
