# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install JDK
      run: chmod +x ./script/installjdk    
    - name: Install JDK
      run: ./script/installjdk
    - name: JAVA_HOME
      run: echo $JAVA_HOME
    - name: HOME
      run: echo $HOME
    - name: JAVA_HOME
      run: java -version
      env:
          JAVA_HOME: $HOME/corretto-8/
          PATH: $JAVA_HOME/bin:%PATH
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      env:
          JAVA_HOME: $HOME/corretto-8/
          PATH: $JAVA_HOME/bin:%PATH
